{
 "title": "Fuse Pod Metrics",
 "description": "Fuse Metrics dashboard",
 "tags": [ "1.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  {
   "title": "Process Start Time",
   "type": "singlestat",
   "description": "Process Start Time",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_start_time_seconds{pod=\"$pod\", container=\"POD\"}*1000"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Fuse.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{pod=\"$pod\"})*100/sum(base_memory_maxHeap_bytes{pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_committedHeap_bytes{pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(base_memory_usedHeap_bytes{pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_cpu_processCpuTime_seconds{pod=\"$pod\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Threads",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{pod=\"$pod\"}",
     "legendFormat": "current"
    },
    {
     "expr": "base_thread_daemon_count{pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "base_thread_max_count{pod=\"$pod\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Camel Exchanges / 1m",
   "type": "graph",
   "description": "Camel Exchanges per minute",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(application_camel_context_exchanges_completed_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Exchanges Completed / 1m"
    },
    {
     "expr": "sum(increase(application_camel_context_exchanges_failed_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Exchanges Failed / 1m"
    },
    {
     "expr": "sum(increase(application_camel_context_exchanges_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Exchanges Total / 1m"
    },
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count{pod=\"$pod\"})",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Camel Processing Time",
   "type": "graph",
   "description": "Camel Processing Time",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_camel_exchange_processing_max_seconds{pod=\"$pod\"})",
     "legendFormat": "Max Processing Time"
    },
    {
     "expr": "sum(application_camel_exchange_processing_min_seconds{pod=\"$pod\"})",
     "legendFormat": "Min Processing Time"
    },
    {
     "expr": "sum(application_camel_exchange_processing_mean_seconds{pod=\"$pod\"})",
     "legendFormat": "Mean Processing Time"
    }
   ]
  },
  {
   "title": "Camel Processing Rate",
   "type": "graph",
   "description": "Camel Processing Rate",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_camel_route_processing_rate_per_second{pod=\"$pod\"})",
     "legendFormat": "Processing Rate (per second)"
    }
   ]
  },
  {
   "title": "Camel Failures & Redeliveries",
   "type": "graph",
   "description": "Camel Redeliveries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_camel_context_externalRedeliveries_total{pod=\"$pod\"})",
     "legendFormat": "Redeliveries"
    },
    {
     "expr": "sum(application_camel_route_externalRedeliveries_total{pod=\"$pod\"})",
     "legendFormat": "External Redeliveries"
    }
   ]
  }
 ]
}